name: Deploy to Vercel

on:
  push:
    branches:
      - master # or main, depending on your default branch name
  pull_request:
    branches:
      - master # or main, depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      NODE_ENV: production
      # Thêm các biến môi trường khác nếu cần
      # NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      # DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run linter
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Create .npmrc file for Vercel deployment
        run: |
          echo "legacy-peer-deps=true" > .npmrc

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}