name: Deploy to Vercel

on:
  push:
    branches:
      - master # or main, depending on your default branch name
  pull_request:
    branches:
      - master # or main, depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Create .npmrc file
        run: |
          echo "legacy-peer-deps=true" > .npmrc

      # Make sure TypeScript and other dev dependencies are installed
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Now we can run the type-check command since we've added it to package.json
      - name: Type check
        run: npm run type-check

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
